project:
  type: website
  output-dir: docs

website:
  navbar:
    background: primary
    search: true
    right:
      - text: "More" 
        menu: 
          - talks.qmd
          - about.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

