project:
  type: website
  output-dir: docs

website:
  title: "Constanza Andaur Navarro"
  navbar:
    left: 
      - href: index.qmd
    background: primary
    search: true
    right:
      - text: "More" 
        menu: 
          - publications.qmd
          - talks.qmd
          - teaching.qmd
          - about.qmd
format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

